## numpy

In [2]:
import numpy as np

In [3]:
x=np.array([1,22,34,5,66])
y=np.array([1,22,34,5,66])
x-y

array([0, 0, 0, 0, 0])

In [4]:
print(x)

[ 1 22 34  5 66]


In [9]:
a=np.array([[1,22,34,5,66],[0, 0, 0, 0, 0]])


In [10]:
a.ndim

2

In [7]:
a.shape

(2, 5)

In [8]:
a.dtype

dtype('int64')

###  大小

In [11]:
a.itemsize

8

In [12]:
a.size

10

In [14]:
a.nbytes

80

In [21]:
a= np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [22]:
a[0,3]

4

In [23]:
a[1,]

array([ 7,  8,  9, 10, 11, 12])

In [24]:
a[:,3]

array([ 4, 10])

In [27]:
a[0,2:5]

array([3, 4, 5])

In [28]:
a[1,5]=100
a

array([[  1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11, 100]])

In [30]:
a[:,2]=-1
a

array([[  1,   2,  -1,   4,   5,   6],
       [  7,   8,  -1,  10,  11, 100]])

### matrix

In [31]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [33]:
np.ones((3,4,5),dtype='float')

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [35]:
np.full((2,4,4),95)

array([[[95, 95, 95, 95],
        [95, 95, 95, 95],
        [95, 95, 95, 95],
        [95, 95, 95, 95]],

       [[95, 95, 95, 95],
        [95, 95, 95, 95],
        [95, 95, 95, 95],
        [95, 95, 95, 95]]])

In [36]:
a.shape

(2, 6)

In [37]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [39]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [42]:
np.random.random_sample(a.shape)

array([[0.52794964, 0.64647009, 0.14366671, 0.69221444, 0.26235096,
        0.13596567],
       [0.20123141, 0.21498503, 0.20154101, 0.94446149, 0.65932087,
        0.56288102]])

In [43]:
np.random.rand(2,6)

array([[0.06586908, 0.76159448, 0.35997074, 0.78262165, 0.44159252,
        0.61192009],
       [0.85084745, 0.67752495, 0.80170569, 0.13611565, 0.76792323,
        0.69708837]])

In [47]:
np.random.randint(-10,10,size=a.shape)

array([[-6, -9,  2, -6, -2,  1],
       [ 2,  7,  2,  9,  7,  1]])

### 重复内容

In [52]:
arr=np.array([[1,2,3]])


In [54]:
r1=np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [56]:
r2=np.repeat(arr, 3, axis=1)
r2

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [64]:
output=np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 设置np内容

In [76]:
z=np.zeros((3,3))
z[1,1]=9

In [77]:
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [78]:
output[1:-1,1:-1]=z

In [79]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [82]:
output_1=output.copy()
output_1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### 计算

In [83]:
a

array([[  1,   2,  -1,   4,   5,   6],
       [  7,   8,  -1,  10,  11, 100]])

In [84]:
a*10

array([[  10,   20,  -10,   40,   50,   60],
       [  70,   80,  -10,  100,  110, 1000]])

In [85]:
a//2

array([[ 0,  1, -1,  2,  2,  3],
       [ 3,  4, -1,  5,  5, 50]])

In [86]:
a/2

array([[ 0.5,  1. , -0.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. , -0.5,  5. ,  5.5, 50. ]])

### 矩阵乘法

In [94]:
a=np.array([[1,2,3],[4,5,6]])
b=np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [95]:
np.matmul(a,b)

array([[12, 12],
       [30, 30]])

In [96]:
np.matmul(b,a)

array([[10, 14, 18],
       [10, 14, 18],
       [10, 14, 18]])

In [100]:
c=np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### statistics

In [101]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
np.min(a)

1

In [105]:
np.min(a,axis=1)

array([1, 4])

In [106]:
np.min(a,axis=0)

array([1, 2, 3])

In [109]:
a[1,2]=1

In [110]:
np.min(a,axis=0)

array([1, 2, 1])

In [112]:
np.max(a,axis=1)

array([3, 5])

In [113]:
np.sum(a)

16

### 改变形状

In [116]:
a.reshape((1,6))

array([[1, 2, 3, 4, 5, 1]])

In [119]:
a.reshape((2,-1))

array([[1, 2, 3],
       [4, 5, 1]])

In [121]:
v1=np.array([1,2,3,4,5,6])
v2=np.array([7,8,9,10,11,12])
np.vstack([v1,v2])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### 文件

In [125]:
file=np.genfromtxt('data.txt',delimiter=',',dtype='int32')

In [126]:
file

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]], dtype=int32)

In [127]:
file > 3

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True, False]])

In [130]:
file[file > 3]

array([4, 5, 6, 7, 8, 9], dtype=int32)

In [134]:
(file > 3) & (file < 5)

array([[False, False, False,  True, False],
       [False, False, False, False, False]])